var lines = [
"Good heavens. A murder? Well apart from this sullen wench murdering good etiquette- Ow.", 
  "I have to go. But if I find one single dog hair when I get back, I'll rub...sand...in your dead little eyes.",
  "[pause] I also need you to buy sand.",
  "I don't know if they grade it, but... coarse.",
  "No, I think Jenga's a game, and...",
  "I assume you would be trying to suck a promotion out of some Russian guy's cock.",
  "...and never will...",
  "And maybe you just got your face kicked off! [Archer puts his foot in Krenshaw's face] That is my foot in your face. Smell the embarrassme- [Krenshaw shocks Archer's foot with a golf cart battery]",
  "That's not... a real place.",
  "Sorry, I was picturing Whore Island.",
  "You're looking for the answer 'yes'?",
  "Then yes.",
  "There's my favorite section head!",
  "Oh, good, you caught the, uh, oh wait, I had something good for this... the... 'Pita Predator'.",
  "...Sorry, let's just call it what it is: food rapist.",
  "[to Pam] I'll throw these doughnuts on the ground so you can pretend they're marbles and you're a hungry hungry... [Pam abruptly shuts the door on Archer] ...hungry hippo.",
  "What are you doing?",
  "Neat. Listen...",
  "'Stir Friday?'",
  "It's all yours. So come let me in the mainframe.",
  "And after I gave you 'Stir Friday!'",
  "I know.",
  "So, obviously, it would be a lot easier for me if you just disabled all that when you left work tonight... somehow.",
  "Ugh, God, everything makes you uncomfortable!",
  "Just the tip?",
  "Just the tip!",
  "How was I supposed to know you're lactose intolerant?",
  "Just the tip. [Pause] Actually, I don't have any cash on me. Could you... get it? I also need cab fare. Awww, Ugly Duckling. Bork Bork.",
  "Well, thanks for nothing, Carol. Now I need to break into ISIS headquarters in a $900 turtleneck. And if it gets ruined I'll make you drink heavy cream, you... Carol!",
  "Wow, that was actually pretty easy! Thanks, new turtleneck! [rips his turtleneck] Aw, f- And thank you, duffle bag!",
  "Holy shit, our security is atrocious. Seriously, it's really bad.",
  "Password. Hmm, password? How about 'Guest'.",
  "No way! It can't be. Jesus Christ, that is just... babytown frolics.",
  "Whoa, I would not push her. That is a big gun and she is baby crazy.",
  "That's why I broke up with her.",
  "See?! All you talk about is baby shit! Because you're baby crazy!",
  "No! I've seen that movie and, spoiler alert, it ends with a closet full of my suits on fire!",
  "Who would want to wear an on-fire suit!",
  "What?",
  "Hey! I was just talking about you, and about how this isn't what it looks like.",
  "Yeah, it's an epidemic.",
  "Is that... sound... is that Jewish?",
  "Um. [long pause] Russian Jewish?",
  "Lana! Krenshaw's a mole! And his real name isn't Krenshaw, it's Kremenski. Definitely Russian! Possibly a Jew! Thoughts?",
  "[shoots Krenshaw] Me? Nothing! You, on the other hand- [Mallory hits Archer with her handbag] What's in there, buckles?",
  "Just half of one. The other half would have missed you. Oh wait...",
  "Johnny Bench called.",
  "Apology accepted. Ass douche.",
  "What?",
  "Make me!",
  "What? Mother, do you see this! This is a hostile work environment.",
  "So, obviously I'm not happy about this whole arrangement, but...",
  "But I wonder what Lana thinks about...",
  "Wow. 'Open purse, remove balls,' huh?",
  "Uh hello! Herpes?!",
  "Wha- Since when?",
  "Well that's just... Excuse us.",
  "Bad joke. And a false alarm.",
  "This is what a real field agent uses.",
  "That's because it's a hypodermic needle and the cartridge is full of a deadly super-toxin called poiso... caine. [puts the pen in Cyril's shirt-pocket] Keep it in here. But be careful, because the cap slips off for, like, no reason.",
  "Oh, I'm crazy? Cyril, you're the one who killed a perfectly good hooker.",
  "Oh my God, you killed a hooker!",
  "No, Cyril, when they're dead, they're just hookers!",
  "Karate?! The Dane Cook of martial arts?! No. ISIS agents use Krav Maga.",
  "Hopefully never. But say you're in a Caribbean bungalow, and you're kind of high, an exotic woman on the bed. Now is she just the high-priced whore you asked for? Or is she an... assassin?",
  "Oh, here's room service. Who ordered champagne?",
  "Exactly. You're baked. You can't remember. But since when does it take three huge surly Jamaican guys to deliver one bottle of champagne?",
  "Or.. Maybe one guy's a new waiter. The second one's training him, and the third's from maintenance, finally off his lazy ass to fix the A.C.",
  "Point is, you come out of the john waving this around... no one's gonna bug you for a tip.",
  "I am the best at this, Rain Man! OK. I'm like...",
  "Well, I don't like to invite that comparison, but yeah, basically.",
  "I'm doing all kinds of stuff, Cyril. I'm shooting the gun, see. I'm driving the car.",
  "So knock yourself out. I'm ejecting.",
  "I totally am.",
  "What? You're black... ish...",
  "Well, what's the word for it, Lana? You freaked out when I said 'Quadroon!'",
  "You imagine it!",
  "Only that he's uncircumcised.",
  "We touched penises.",
  "What's weird about that? I'm not Jewish but I am circum-",
  "Oh Lana, I think we both know it works just fine.",
  "Uh, none-of-your-business-ing. And what kind of spy agency scrimps on a freaking shredder?",
  "No. I missed on purpose.",
  "Lana, call Kenny Loggins... 'cuz you're in the Danger Zone.",
  "Then unperforate my eardrum.",
  "Conway?",
  "Are there more bad guys behind me?",
  "You dick.",
  "You said no dates.",
  "Well, your mouth did.",
  "Um, phrasing?",
  "All I've had today is, like, six gummy bears and some scotch.",
  "[as Mallory rings a dinner bell] Wow. Forgot how much I hate that.",
  "[as everybody laughs] Mother!",
  "Woodhouse! What are you doing?!",
  "What, at the table?!",
  "Like people?!",
  "What?! Look, he thinks he's people!",
  "Only if the back of his skull picked that exact moment to explode outwards.",
  "[carrying Elke's body] Cyril, I paid her, I get to carry her corpse.",
  "God, Cyril, that was... [gunshot] pathetic.",
  "No! Have you ever seen CSI? This is already like Clue Town.",
  "Wha... oh.",
  "But this gun-it was a gift.",
  "You don't know.",
  "We still didn't get the UN contract.",
  "[Wearing only a towel and baseball catcher's mask] WOODHOUSE! Do we have any lube? Like at this point even some olive oil would [finds his mother in the living room] help me get that drawer unstuck.",
  "Not abnormal, just... gay!",
  "No! They're just costumes.",
  "...Doesn't it?",
  "And I suppose that makes it better?",
  "Jesus, Krieger, you're still taping bum fights?",
  "And it makes you temporarily gay?",
  "I'll pass.",
  "Way the Christ out in the Everglades burying some Dominican guy's rooster!",
  "Mine always said, 'Sterling, come in here and check me for lumps.' Holy shit, was that out loud?",
  "Yeah, like I told you he would! You idiot!",
  "Out macho a gay guy? Oh my stars!",
  "Yeah? Well, I'm dangerous and I'm going to win and GAY SEX!",
  "So, are you two even really gay!?",
  "How do you say 'The Hulk' in Spanish?",
  "Gay.",
  "Do you have a word for 'gay'?",
  "Gayer! Jesus, Spanish! Our jobs aren't enough; now you gotta take our words?",
  "[Stifling laughter] Woodhouse: he's all tied up somewhere, sc-scared and alone. PROBABLY DEHYDRATED!",
  "Cyril, c'mon. Worst case scenario, her cover got blown and Skorpio's raping her senseless before he chops her battered corpse up into fish food.",
  "Lana. Lana! LANA!!!",
  "Danger Zone.",
  "Unkempt bush!? You're one to talk.",
  "I'd say that's fairly classic her.",
  "Nice read, Velma.",
  "To get my turtleneck! I'm not diffusing a bomb in this.",
  "Uh... it didn't?",
  "There's your bomber: Beardsley McTurbanhead.",
  "I don't know!",
  "Well, obviously!",
  "These were all I could find. I'm thinking: goggles, yes; shovels, I don't know how or why we'd use them.",
  "[Wearing night-vision goggles and holding a shovel] Unless it involves night-shoveling.",
  "Cyril. Cyril! CYRIL!",
  "I'm rescuing Lana, as usual!",
  "Frickin' ODIN.",
  "About a gillion.",
  "A gillion gay, little copy-cats.",
  "I didn't invent the turtleneck, Lana. But I was the first to see its potential as a tactical garment. The Tactical Turtleneck, Lana. The... Tactleneck!",
  "Maybe you should've thought about that before you blew the damn drop!",
  "Name dropper.",
  "ODIN doesn't beat Sterling Archer! Only Sterling Archer beats... [He trails off as he realizes he's lost the target.]",
  "Do you wanna shut your big, fat, negative-wordsy mouth?!",
  "Yeah, 13 years' worth.",
  "No, I loved it. Uh... made a lot of good friends. [Quick cutaway to a young Archer sitting alone on the lacrosse field] Family, almost, is what they were.",
  "Oh, please. I bet she doesn't even miss me.",
  "Why? So you can smash that too?",
  "[Talking over Lana] Because I'm pretty sure I'm financially responsible for the furnishings!",
  "Mother burned me?",
  "Oh, my god, that's classic her.",
  "Let's talk this out.",
  "Ex-boyfriend, I bet.",
  "Yeah, he's not coming back. That chick was, like, the Pelé of anal.",
  "[To Lana] Oh, OK! Then I guess just pout!",
  "Yeah, but with starlets, models. Oh, and one time, two actual princesses.",
  "Yeah. They were sisters.",
  "You just destroyed my innocence!",
  "12!",
  "Hey! Kidnappers! Super not in the mood for this right now!",
  "I know, right? Totally McQueen!!",
  "What is it, the Alabama of Europe?",
  "Fuck you, Switzerland.",
  "Well, obviously before; after was all gendarmes and dick stitches.",
  "I saved her life! Go ask that dick I set on fire.",
  "No. Just incredibly pissed off!",
  "I don't have to try [pause] Shit, whatever. Move. [walks away]",
  "Freaky!",
  "Rabbert Klein?",
  "It's all yours.",
  "[talking about a mind control chip placed in a rabbit] Can you put it in a person's brain?",
  "Not the rabbit, idiot; the chip.",
  "Without killing the person?",
  "Why do we have so many damn dolls?",
  "Cyril, better pill up; you're assisting Krieger with the surgery.",
  "You're good at math.",
  "Can't hurt.",
  "Oh, for fuck's sake, Krieger! You're about to perform brain surgery!",
  "Okay, it's over, and... you're sure you don't wanna marry that woman?",
  "Tell me.",
  "...Um... okay...",
  "Um, can we give Lenny the rabbit?",
  "...Sure thing. Go to town.",
  "Um. Is he always gonna be like this now because I feel bad.",
  "Hey, you idiots wanna hear my plan or not? [Silence] Alright... Suggestions.",
  "What are we talking about... Stopping my mother from selling ISIS to ODIN!",
  "My plan is to crowdsource a plan!",
  "I feel terrible.",
  "Oh, hey, speaking of fifth...",
  "Because I told you to buy Lemon Curd! Now what am I going to spread on my toast, Your tears?!",
  "[with Woodhouse] That's disgusting. If I wanted to look at your bare feet, Woodhouse, I'd sneak in and do it while you were asleep.",
  "What do you mean, 'Reserved'?",
  "Thank you, certified air boat mechanic!",
  "WOOOHOOOOOOO!!! THIS MUST BE WHAT IT'S LIKE TO HAVE SEX WITH ME!",
  "Burt Reynolds is my spirit guide!",
  "No, I'm pretty sure it was 'shut up!'",
  "That's just great. She gets dinner and Dixieland and laid. And I get mosquitoes and no beer and... not laid. How could this get any... [alligator surfaces and growls] LET ME FINISH... worse. You ruined it. You ruined the moment.",
  "You realise you're in huge trouble?",
  "And now I have to spend my first Friday off in forever devising some bizzare punishment for you?",
  "So don't be surprised if you end up eating a whole bunch of... spiderwebs.",
  "He might have a tiny hangover...",
  "You want me to take a baby to a murder?",
  "Yeah and what is it? Two-Thirty?",
  "Render the salad unto Caesar!",
  "What comes after infuriated?",
  "It's like it's made out of Wolverine's bones.",
  "Krieger, who's virtual girlfriend is so real that the state of New York is allowing him to legally marry her!",
  "Get me drunk enough and I might have sex with you.",
  "No! Its a catch-22. The amount of alcohol it would take would literally kill me!",
  "But I do want to see how many pool balls you can fit in your mouth.",
  "Who am I, Alan Turing?",
  "[Spotting Spelvin's bikini-clad Asian ninja bodyguards] I'm suddenly much less angry.",
  "Damn it, Cyril! You said they were sexy!",
  "Am I getting some signals?",
  "Come back to me, I can do better.",
  "Come, Kriegerbots, avenge your fallen comrade! What voice is that? Is that from Bullwinkle?",
  "[Eavesdropping] Oh yeah? While you're tangled in a half-mile of shit covered tape? ... Frickin' actresses.",
  "[Bursting in with his gun drawn] Freeze!",
  "Wait, seriously don't open it?",
  "Oh. I thought you were being sarcastic.",
  "[Holding a radioactive vial] Looking for this? Or maybe the lead container I probably should've kept it in?",
  "Yup, Stage Two breast cancer. Yeah, I mean it's not as bad as stage three or four. But, obviously not as good as no cancer.",
  "It's a pink ribbon, I have breast cancer.",
  "Yes.",
  "[Laughing weakly] Excuse me.",
  "[Between punches] I'm trying... to stay positive... both mentally... and spiritually... Brett!",
  "[To Woodhouse] Macrobiotic food. Find out what that is and start cooking it.",
  "Wow, what a pussy. I could barely even keep up, he was spilling the beans so fast.",
  "Well excuse me, Lana. It's a rampage.",
  "Don't you worry, Ruth... I'm gonna make them pay for it.",
  "Cry havoc and let slip the hogs of war!",
  "Whatever farm animal of war, Lana! Shut up!",
  "[Placing shells in a sawed-off shotgun] Nope, but a hundred people surveyed, number one answer's on the board...",
  "Name the douchebag who's in charge!",
  "Vincent Van Go-fuck-myself. Survey says! [Blows his kneecap off]",
  "What, Lana!? I said it was a rampage!",
  "Save it for the fast money round, paddy! [Moves on to second mobster] Hundred people surveyed, number one answer's still on the board, name the douchebag who's in charge!",
  "[Imitating buzzer] Eh-Eh! Need an answer!",
  "Hmm, cock-flavored spit. Well, you never know what's gonna be on the board. Lemme see cock-flavored spit! [Blows the second mobster's kneecap off] That's two strikes!",
  "One more and the innocent Honduran janitors get a chance to steal the bank! [To Hondurans] I'm just gonna assume you guys don't actually know what goes on here. I hope that doesn't sound racist. [Moves on to the third mobster] Okay, kid...",
  "LANA! You're in the isolation booth! [To young mobster] Looking for the douchebag who's in charge!",
  "[Makes buzzer noise again] Eh-Eh! [Shoots first mobster, killing him]",
  "Mikey, you gotta listen to me, buddy... I have breast cancer.",
  "What have I been doing?",
  "Ew!",
  "Still, though.",
  "What's to prove? It's free labor.",
  "Tum again?",
  "How long do I need to keep them on?",
  "What happened to thirty seconds?!",
  "Well, now you know how Babou feels.",
  "Yes!",
  "Because you're just wearing it to piss me off!",
  "Yes, so take it off! We look totally gay!",
  "Well, I'm not!",
  "Shut up! That vest is bullet-proof!",
  "But it is, y'know, a vest.",
  "Uh, I guess it's cause he's doing all that other awesome stuff, thanks mother.",
  "Uh, [Raises his glass] pretty sure you just answered your own question.",
  "Hey.",
  "HEY! [pause] Actually, that would not surprise me.",
  "Balls.",
  "I have a plan to get the money back. [See's Ray carrying a bag of toiletries] That doesn't include you taking my hotel toiletries!",
  "Yes, I am.",
  "Rob the casino.",
  "There's a zoo here?",
  "He's headed for the coast road!",
  "Shooting at his tires so he loses control and drives off the cliff!",
  "Yes, Lana, with the... Dammit!",
  "I am getting off, I love this.",
  "Don't 'lesson one' me, Barry.",
  "Piece of-! How are you a super power!?",
  "Oh that is bullshit! Who would break into this shit hole!?",
  "Yeah right, like you've got plans.",
  "Hey. Fuck you, you douche bag.",
  "[sounding like Cyril] Hello...",
  "I... uh...",
  "Phrasing, Mother!",
  "You realise I can never unhear that? … Why are you crying?",
  "No! You swallowed a pool ball?",
  "Pam, wait! I had something… what was it? … Uh, something about stripes and solids.",
  "It's ok, it was just cancer sex.",
  "So you! [Smack] Can you hack into the KGB servers?",
  "Wait, does Canada even have a spy agency?",
  "Wha- why? Haha, it's Canada.",
  "Is anybody hit? Not really the explosive climax I thought it was gonna be.",
  "[To Barry] How are you not dead?",
  "[While being choked by Barry] Wow, Barry, you're like super-strong!",
  "The core concept, I guess.",
  "So excuse me for needing some time to grieve.",
  "Apparently that's my grieving process.",
  "A ruse? Hi, it's the 1930s. Can we have our words and clothes and shitty airplane back?",
  "Call you back, 1930s. And, hey, watch out for that Adolf Hitler. He's a bad egg.",
  "Wow, if the five year old me knew that, he'd get a huge boner.",
  "Noah, I'm half drunk and slathered in every bodily fluid there is... so yeah... this is about as Pirate Kingy as I'm going to get so brief away... Noah... Good Morning.",
  "Noah, I've still got four bullets.",
  "Do you know what ‘License to kill' means?",
  "The world holds its breath.",
  "How should I know?",
  "Who am I, Karl Landsteiner?",
  "Your exact words, Pam: “Dr. Charles Drew or I will eat a bag of dicks”!",
  "Thanks, Human Shield.",
  "Since ever!",
  "[Singing] Eastbound and dowwwwwn!",
  "Which doesn't even merit a response.",
  "I know, it's like, the world's slowest elevator.",
  "$9000.",
  "Lowest quote I got.",
  "I know. It's just basically putting a pole where the garbage chute is, but all the co-op people were like, 'But what are we going to do with all the garbage?'",
  "Yeah, if you're coming in hot, I know, it's a win-win.",
  "Exactly.",
  "Preaching to the choir, pal.",
  "Yeah. What?",
  "HOLY SHIT! Burt Reynolds!",
  "I'm sorry, I can't hear you over the sound of my giant, throbbing erection!",
  "It's gone. I'm all ears.",
  "Yeah, he... kinda is.",
  "Or wearing such shitty clothes.",
  "[On Cyril being a field agent] The last time I tried to train him resulted in a dead hooker in my trunk!",
  "There easily could have been!",
  "Well look on the bright side.",
  "Which is what?",
  "Its a figure of speech.",
  "..yes!",
  "Not totally, he has a tell-tale shimmer.",
  "Jai alai?",
  "What?",
  "Are you kidding? After seeing a tiger get murdered? Lana, I'm not in the mood!...I mean, if you want to, I can watch while you masturbate, but just so you know, my heart's not going to be into it. It's going to be with that tiger's family...But, you know...go ahead and start.",
  "Apparently!",
  "AGH! Eat a dick, jungle!",
  "For a second there I thought you were a crocodile on a three wheeler.",
  "Right, how scary would that be?",
  "Speaking of excellence, did you hear we met a tiger? But...he was murdered.",
  "I've always wanted to fight on top of a moving train.",
  "Thanks, Freddy Foreshadowing.",
  "I'm looking for a terrorist and an ocelot!",
  "Okay... it's not though.",
  "[Describing an Ocelot's paw-prints] They look just like a housecat's, but bigger and awesomer.",
  "[to Babou the ocelot while handcuffed in a police car] They called you exotic. Which is just people talk for awesome. Which you are, which is why I am so happy I saved your life, buddy. [Babou growls and squeaks to him] Don't worry, probably just thousands of dollars in fines, maybe a little bit of jail time, hopefully just probation. [Babou leans forward and urinates on the car seat next to Archer. Archer speaks in a strained voice] Totally worth it. [Babou growls] No, Babou, that was all sarcasm. [more growls] YES, ALL OF IT, YOU FOX-EARED ASSHOLE!",
  "[Climbing to the top of the moving train] This is going to be awe- SHIIIIITT! [The wind causes Archer to lose his gun] AHHHH! The dust! It's like being shot in the eyes by a... glitter gun! [Puts on night vision goggles] There, that ought to do it. Okay, let's try this aga- [Gets blinded by the lights of a passing train] AAARGHSHIIIITTTT! My retinas are seared like tuna steaks!!! ALL I WANT IS TO FIGHT ON TOP OF A TRAIN! IS THAT TOO MUCH TO ASK?! [Switches off the night-vision on his goggles] The good news is, now I'm furious.",
  "Paging Doctor Boy, Doctor Birthday Boy!",
  "Does no one seriously know what today is?",
  "Is it going to kill everyone?",
  "It does know my name!",
  "Thanks, Dodge!",
  "It makes the Mach-5 look like a vagina.",
  "Corinth is famous for its leather!",
  "[staring at his back-lit, in-car minibar] It's like looking into the face of God.",
  "[interrupting] Possible.",
  "It's this Corinthian leather!",
  "Black, powerful, sexy. Like if Ron O'Neal was a car.",
  "Well, unless it was the creepy-old-people-bondage-sex police, why would anyone break in here and shoot him?! No answer? Okay, let's ask him. [Pulls off mask]",
  "Uh...",
  "The what?! Wait, doesn't Italy use a king?",
  "I... yeah, exactly. Good question.",
  "I have a question, Mother. Why does this chair have no seat... and WHAT... IS IN HIS ASS?!",
  "Mother! What is in his ass?!",
  "Not in a dead prime minister's ass!",
  "Lawyer up. Call the cops.",
  "Oh, and hit the throttle on the bourbon because I'm gonna have to, uh, bust you in the face a couple times.",
  "Self-defense, Mother! It's your only shot! We'll have to uncuff him and 'de-dildo' him, obviously... Smash up the furniture like he was chasing you all rapey. Fortunately, he's Italian so that shouldn't be too hard to sell.",
  "I bet I'll never be able to have sex again without thinking about this! I bet I won't even be able to eat spaghetti and meatballs. Oh God!",
  "I could eat. Not necessarily spaghetti and meatballs, but, you know, not necessarily not spaghetti and meatballs. I mean I really like spaghetti and meatballs. Man, if I don't get some spaghetti and meatballs, I may literally die.",
  "Sucks, because I bet he knew how to make sauce.",
  "What is your problem with the Irish?",
  "Yeah, besides that. Wait, seriously? They were Nazis?",
  "Well, they're not Japanese...",
  "You got a potato?",
  "He literally might be, yes.",
  "Ray, to be honest, I'm kind of having second thoughts about this whole thing.",
  "Okay, now I'm having third thoughts.",
  "It would be rude not to eat her pie, which I assume is not only hot, but also moist... Although hopefully not flaky.",
  "Ray, I'm having fourth thoughts.",
  "Fifth thoughts!",
  "No! I... I swear, this was just an extremely unlikely mishap with the barbed wire.",
  "Because I wasn't sure if you knew what 'amenable' actually meant, until you followed it up with 'nonplussed.'",
  "The truth is that your seemingly effeminate brother is, in fact, a highly trained secret agent.",
  "I feel sick. What's happening? Do I have cancer again?",
  "That's a thing?",
  "Ha ha, phrasing.",
  "For I am a sinner in the hands of an angry God. Bloody Mary, full of vodka, blessed are you among cocktails. Pray for me now and at the hour of my death, which I hope is soon. Amen.",
  "If anyone found out, I'd literally die of shame.",
  "I don't care, Pam! [Pause] Having said that, would you please come into this dirty toilet stall and have sex with me?",
  "Who hunts dogs?",
  "Where did you learn all that stuff?",
  "Really hoping that's not relevant.",
  "And instead of doing my job, I was here... Half-drunk and having amazing sex.",
  "Wait, why did you emphasize 'serial'?",
  "[To Cyborg-Katya] That's your original skin, right?",
  "What?",
  "Can you close your eyes? It feels like I'm banging tail-lights on a country road.",
  "Which makes me feel even more terrible, since I'm going to puke it back up in five- [burps] one minutes...",
  "Is...? Okay, I'll bite.",
  "Krieger!",
  "Vacuum Cleaner puns?! Really?!",
  "Barry",
  "Will you shut up!",
  "Uhh! I say all sides by idiots",
  "Fuck you, space.",
  "Happy, Cyril?! You just destroyed Alderaan!",
  "Happy accident.",
  "A black astronaut, Cyril! That's like killing a unicorn!",
  "Don't, Don't you say it",
  "What, really?",
  "[Seeing Cyril's orange snow clothes on the ground] Okay, so...really don't know what to make of that. Unless...[Looks around] Wait, no, no. Get it out of your head. Preadator only hunts in tropical jungles...I assume...and desperately hope.",
  "Do you want to live through the Rise of the Machines, which you won't, because no one will?"
];

var lana_lines = [
"You're looking for Predator aren't you? A, he's invisible.",
"Don't take this the wrong way, but I'm trying to figure out how you're going to be an effective field agent.",
"Yeah, gotta give him a sploosh.",
"On your knees, hands behind your head, and toss out that weapon! But not in that order.",
"As what? Russia's only black woman?",
"You turned Archer loose with four million dollars in a casino?",
"Chain smoking joints the size of tampons.",
"Oh my... you're getting off on this!",
"If your aunt has balls, she'd be your uncle.",
"And?",
"This isn't the Sheriff's department where you get to wear a windbreaker and go on a ride-along. This is highly classified covert ops.",
"Well if you like the collar, you're gonna love the cuffs.",
"What's your third biggest fear?",
"What's a brain aneurysm have to do with walking around in a swamp?",
"[Opens a cooler of nothing but beer] You're shitting me.",
"How could an airboat be selfish?",
"He's attacked nuclear power plants, hydroelectric dams, and whaling ships.",
"Is that a friggin' candy bar?",
"Did you see me holding that baby?",
"'Taking' as in to get this job I have to have sex with you?",
"No, she looks like she's just turning 18.",
"Good thing you know how to cheat.",
"Hi, if any of you men want to have sex with me [Cyril gasps] come to my office and take a number.",
"Barry, you might want to call the cleaners. [SMASH, Lana looks down at unconscious Barry] Because there is lamp everywhere.",
"Didja wanna finish that thought?",
"Did Cyril run past here sobbing in a woman's bathrobe?",
"WHAT!!!?",
"Noooo... Sudden is wanting your girlfriend to move in with you after only 4 months.",
"Thanks, no. I'm allergic to cat piss.",
"A non-circumsized Jewish guy, that's not weird to you?",
"It doesn't work like that.",
"Ish!?",
"(sarcastic) Imagine that!!",
"Where? Outside a clown college?",
"I blew jack shit!"
];

// Grab the quote indexes we've used before from local storage
var usedQuotes = (localStorage.usedQuotes) ? localStorage.usedQuotes.split(",") : [];

// Save original position of quotes
for (var l = 0; l < lines.length; l++ ) {
  lines[l] = [l, lines[l]];
}

// Remove used quotes from the list of quotes
var offset = 0;
for (var q in usedQuotes) {
  q = parseInt(q)
  for (var l = 0; l < lines.length; l++) {
    if (q == lines[l][0]) lines.splice(l, 1);
    break;
  }
}

// Grab the quote
var quoteIndex = Math.floor(Math.random()*lines.length);

// Save the quotes we've used back to local storage
usedQuotes.push(lines[quoteIndex][0]);
localStorage["usedQuotes"] = usedQuotes;

// Show the quote
$("body").children("h2").html(lines[quoteIndex][1]);
